### ISSUE TITLE
YAML Granule Description File or "External visitor/handler?"

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREPandas#33]
1. Would it be possible to have a more generic granule i/o that reads an external YAML file to get the info it needs to load data from a granule?
2. Alternatively, could we pass an appropriate object-maker, function, or object into a STAREPandas i/o call that does the loading, but is not part of the STAREPandas package? This would allow end users to write granule-type i/o code and pass that into a STAREPandas object to access the data they need. The key would be to make sure that the correct interface is provided by the user-provided code.

**Comment by michaelleerilee** [comment]
@NiklasPhabian Thoughts?

**Comment by NiklasPhabian** [comment]
I really like this idea. 

I am slightly scared though of not doing this right though. I previously ran several times into granules that didn't fit my previous model of granule abstraction forcing me to re-write

e.g.
1. More than one resolution per granule e.g. in MOD09
2. Geolocations in companion file rather than in the granule itself e.g. in VNP02DNB
3. More than one scan/swath per granule. e.g. in the XCAL datasets

I was hoping to add a few more granule types with our current implementation to get a level of confidence that we are abstracting effectively (and thus capture all that has to be specified in the YAML)

**Comment by NiklasPhabian** [comment]
@michaelleerilee is this what you ended up implementing in granule_democracy?

**Comment by michaelleerilee** [comment]
Use the granule factory approach. Coming up with our own description language is too big an effort.
